[package]
name = "iwc-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
iwc-arena = { version = "0.1.0", path = "../iwc-arena" }
smol_str = "0.2.0"
